version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '.'
    schedule:
      interval: 'daily'
    reviewers:
      - sepsep
      - DerrickGHW
      - serenayanbolt
      - justinBolt1987